Description: >
  Juan Manuel Lovera

Parameters:
  EnvironmentName:
    Description: An environment name that will be prefixed to resource names
    Type: String
Resources:
    WebServerSecGroup:
        Type: AWS::EC2::SecurityGroup
        Properties:
          GroupDescription: Allow http to our hosts from local only
          VpcId:
            Fn::ImportValue: !Sub "${EnvironmentName}-VPCID"
          SecurityGroupIngress:
            - IpProtocol: tcp
              FromPort: 80
              ToPort: 80
              CidrIp: 0.0.0.0/0
          SecurityGroupEgress:
            - IpProtocol: tcp
              FromPort: 0
              ToPort: 65535
              CidrIp: 0.0.0.0/0
    EksClusterRole:
        Type: AWS::IAM::Role
        Properties:
            AssumeRolePolicyDocument:
                Version: '2012-10-17'
                Statement:
                  - Effect: Allow
                    Principal:
                        Service:
                            - eks.amazonaws.com
                    Action:
                        - sts:AssumeRole
            RoleName: KubernetesRole
            ManagedPolicyArns:
                - arn:aws:iam::aws:policy/AmazonEKSClusterPolicy
    Kubernetes:
        Type: 'AWS::EKS::Cluster'
        Properties:
            Name: prod
            Version: '1.14'
            RoleArn: ->
                !GetAtt EksClusterRole.Arn
            ResourcesVpcConfig:
                SecurityGroupIds:
                - Ref: WebServerSecGroup
                SubnetIds:
                - Fn::ImportValue: !Sub "${EnvironmentName}-PUB1-SN"
                - Fn::ImportValue: !Sub "${EnvironmentName}-PUB2-SN"
        DependsOn: EksClusterRole