env:
  es6: true
  node: true
extends: "eslint:recommended"
rules:
  {
    "no-const-assign": "error",
    "no-this-before-super": "error",
    "no-undef": "error",
    "no-unreachable": "error",
    "no-unused-vars": "error",
    "constructor-super": "error",
    "valid-typeof": "error",
  }
parser: babel-eslint
parserOptions: { ecmaVersion: 8 }
