apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-deployment
spec:
  selector:
    matchLabels:
      app: node
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: node
    spec:
      containers:
        - name: jmalovera10-devopscapstone
          imagePullPolicy: Always
          image: jmalovera10/devopscapstone:latest
          ports:
            - containerPort: 80
              protocol: TCP
