apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-deployment
spec:
  selector:
    matchLabels:
      app: node
  replicas: 1
  template:
    metadata:
      labels:
        app: node
    spec:
      containers:
        - name: jmalovera10-devopscapstone
          image: jmalovera10/devopscapstone:latest
          ports:
            - containerPort: 80
